theme:
    resource: "@ThemeBundle/Controller/"
    type:     annotation
    prefix:   /

first:
    resource: "@FirstBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
